'use strict'

// Don't forget the comma! No trailing slashes
// protocol://url.domain.ext

const sites = [
  { url: 'https://wiki.xxiivv.com', title: 'xxiivv', type: 'wiki', author: 'Devine Lu Linvega', contact: 'aliceffekt@gmail.com', rss: 'https://wiki.xxiivv.com/links/rss.xml', feed: 'https://wiki.xxiivv.com/twtxt.txt' },
  { url: 'http://estevancarlos.com' },
  { url: 'https://electro.pizza', title: 'electro pizza', type: 'blog', author: 'rho', rss: 'https://electro.pizza/feed.xml', feed: 'https://electro.pizza/twtxt.txt' },
  { url: 'https://ianjbattaglia.co' },
  { url: 'https://avanier.now.sh/wiki', title: 'Ath', type: 'wiki', author: 'Josh Avanier', contact: 'joshavanier@protonmail.com' },
  { url: 'http://kaemura.com' },
  { url: 'https://liamcooke.com' },
  { url: 'https://electricgecko.de' },
  { url: 'https://wichniow.ski' },
  { url: 'https://hraew.autophagy.io' },
  { url: 'http://evenunto.net' },
  { url: 'https://anxl.faith' },
  { url: 'https://xvw.github.io', title: 'xvw.github.io', type: 'blog', author: 'Xavier Van de Woestyne', contact: 'xaviervdw@gmail.com', rss: 'https://xvw.github.io/atom.xml' },
  { url: 'https://heracl.es' },
  { url: 'https://felipecortez.net' },
  { url: 'http://luminghao.com' },
  { url: 'https://turelio.github.io' },
  { url: 'https://spaceshipsin.space', title: 'spaceshipsin.space', type: 'hybrid', author: 'Gaeel Bradshaw-Rodriguez', contact: 'gaeel@spaceshipsin.space' },
  { url: 'https://log.lectronice.com', title: 'lectrolog.', type: 'blog', author: 'lectronice', contact: 'i.love.spam@lectronice.com' },
  { url: 'https://craze.co.uk' },
  { url: 'https://shaneckel.com' },
  { url: 'https://cblgh.org' },
  { url: 'https://ellugar.co', title: 'ellugar', type: 'wiki', author: 'afk', contact: 'afk@ellugar.co', rss: 'http://feeds.ellugar.co/ellugar-logs' },
  { url: 'http://hur.bet' },
  { url: 'http://chigby.org' },
  { url: 'https://longest.voyage' },
  { url: 'https://palomakop.tv' },
  { url: 'https://travisshears.com' },
  { url: 'https://v-os.ca' },
  { url: 'http://secretinternet.club' },
  { url: 'https://jmandel.xyz' },
  { url: 'https://systems.ws' },
  { url: 'https://jamesin.space' },
  { url: 'https://nathanwentworth.co' },
  { url: 'https://eswat.ca' },
  { url: 'https://uonai.space' },
  { url: 'http://controls.ee' },
  { url: 'https://wasin.io' },
  { url: 'https://inns.studio' },
  { url: 'http://kokorobot.ca' },
  { url: 'https://ameyama.com', title: '雨山', type: 'blog', author: 'jrc03c', contact: 'josh@ameyama.com', rss: 'https://ameyama.com/blog/rss.xml' },
  { url: 'https://wake.st' },
  { url: 'https://xarene.la' },
  { url: 'https://alex.zyzhang.me' },
  { url: 'http://bildwissenschaft.vortok.info' },
  { url: 'https://jakofranko.github.com' },
  { url: 'https://aeriform.io' },
  { url: 'http://blog.lucasdidthis.com' },
  { url: 'http://npisanti.com', title: 'npisanti.com', author: 'Nicola Pisanti', contact: 'nicola@npisanti.com', rss: 'http://npisanti.com/journal/rss.xml' },
  { url: 'https://underscorediscovery.ca' },
  { url: 'https://drisc.io', title: 'drisc.io', type: 'wiki', author: 'Cory Driscoll', contact: 'cory@drisc.io', feed: 'https://drisc.io/hallway/twtxt.txt' },
  { url: 'https://neufv.systems', author: 'Nuel van Gelder de Neufville', feed: 'https://neufv.systems/twtxt.txt'},
  { url: 'https://ricky.codes' },
  { url: 'https://maxdeviant.com' },
  { url: 'https://tynandebold.com' },
  { url: 'http://gytis.co' },
  { url: 'https://nomand.co' },
  { url: 'http://memoriata.com' },
  { url: 'https://mmm.s-ol.nu' },
  { url: 'https://chad.is' },
  { url: 'https://smidgeo.com/bots' },
  { url: 'https://iko.soy' },
  { url: 'http://atelieroilandsugar.com' },
  { url: 'https://magoz.is' },
  { url: 'https://szymonkaliski.com' },
  { url: 'https://phse.net', title: 'phse.net', type: 'blog', author: 'Stephen Lindberg', rss: 'https://phse.net/post/index.xml' },
  { url: 'https://rosano.ca' },
  { url: 'https://soyboysky.github.io' },
  { url: 'https://gndclouds.cc' },
  { url: 'https://xuv.be' },
  { url: 'https://dsdshcym.github.io' },
  { url: 'https://wiki.chronica.xyz', title: 'chronica', type: 'wiki', author: 'Chris Kipp', contact: 'ckipp@pm.me' },
  { url: 'https://boffosocko.com' },
  { url: 'https://hex22.org' },
  { url: 'https://patrikarvidsson.com' },
  { url: 'https://sophieleetmaa.com' },
  { url: 'https://xinniw.github.io' },
  { url: 'https://mboxed.github.io/forida' },
  { url: 'https://letters.vexingworkshop.com' },
  { url: 'https://tom.org.nz/about' },
  { url: 'https://teknari.com' },
  { url: 'https://colectivo-de-livecoders.gitlab.io/', title: 'Colectivo de Livecoders', type: 'blog', author: 'CLiC', contact: 'https://t.me/clic_laplata' },
  { url: 'https://www.madewithtea.com', title: 'madewithtea.com', type: 'blog' },
  { url: 'https://amorris.ca', title: 'amorris', author: 'Aaron Morris', type: 'blog', feed: 'https://feed.amorris.ca/hallway.txt' }
]
